### ISSUE TITLE
Issue with cache manager and recorder feature

### ISSUE THREAD

**Issue by henryso** [kalrish/luatex-lua-module-cache-manager#2] opened 2016-02-19 22:45 UTC
If I run

```
make clean
make
make
```

Then on the final run, it will segfault (I am using LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238) under Linux).

By process of elimination, I have traced this to the use of the `-recorder` flag.  If I remove that flag, it stops segfaulting.  This might be a bug with LuaTeX, but since it doesn't happen when I'm not using the cache manager, I thought I'd ask here first.

**Comment by kalrish** [comment] 2016-02-19 23:08
Oh, thank you! I had been experiencing the same problem, but hadn't figured out it was related to the recorder feature. All I knew was that the segfault happened at `loadfile` when the cache file existed.

For now, I have modified the Makefile so as to avoid using the feature (commit 4657d17), but the issue is still worth investigating.

My first guess has been that, since Lua strings are not null-terminated, LuaTeX runs out of bounds when examining the path of the file that's opened. However, appending a null character to `cache_file_path` doesn't solve the problem and it still segfaults.

**Comment by kalrish** [comment] 2016-02-19 23:21
Perhaps LuaTeX doesn't handle well the recorder feature at the Lua initialization script stage (since it is run "so early"…). In fact, if the script is not run as a initialization script but as normal Lua code (by executing `lualatex --interaction=nonstopmode --halt-on-error --file-line-error --recorder --jobname=main -- '\directlua{dofile("lua-module-cache-manager.lua")}\input{main.tex}'`, after changing `lua-module-cache-manager.lua` to use the `luatexbase` interface for callbacks), everything is fine.

**Comment by henryso** [comment] 2016-02-19 23:37
Try putting the loadfile bits in a callback function registered to 'start_run'.  Maybe that will work.

**Comment by kalrish** [comment] 2016-02-19 23:47
You're right, it works that way.

… but this doesn't seem the right solution; if the problem is indeed in LuaTeX, it's LuaTeX that should be fixed. I have been diving into the source code, but haven't yet found my way through it.

**Comment by kalrish** [comment] 2016-02-21 01:09
I have opened a [bug report](http://tracker.luatex.org/view.php?id=964) — let's see how it goes.

**Comment by kalrish** [comment] 2016-02-26 09:08
It was indeed a bug. Luigi Scarso has fixed it.

**Closed as completed by kalrish** 2016-02-26 09:08 UTC
